### ISSUE TITLE
Website https://academy.perspect.it/ has endless redirects for Dutch viewers

### ISSUE THREAD

**Issue by michielbdejong** [joopringelberg/perspectives-core#2]
For me, https://academy.perspect.it/ redirects (with JavaScript?) to https://academy.perspect.it/nl/ 
Which redirects (with a 302) back to https://academy.perspect.it/

Workaround: Visit https://academy.perspect.it/en/ instead

**Comment by joopringelberg** [comment]
Thank you Michiel, I cannot do it right now but will fix it.

**Comment by joopringelberg** [comment]
Website no longer exists.
